name: Build RPM and DEB packages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build DEB package
    - name: Install dependencies for DEB build
      run: |
       # sudo apt-get upgrade
       # sudo apt install -y build-essential devscripts debhelper

    - name: Build DEB package
      run: |
        cd ./debbuild/
        dpkg-deb --build . ./kitimist-deb-package-${{ github.run_id }}.deb
       
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: kitimist-deb-package-${{ github.run_id }}
        path: ./debbuild/kitimist-deb-package-${{ github.run_id }}.deb

    # Build RPM package
    - name: Install tools for RPM build
      run: |
        sudo apt install -y rpm
        
    - name: Build RPM package
      run: |
        cd ./rpmbuild/SPECS
        rpmbuild -ba regular_files_from_etc.spec

    - name: Check RPM file existence
      run: ls -la ./rpmbuild/RPMS/x86_64/

    - name: Upload RPM package
      uses: actions/upload-artifact@v4
      with:
        name: kitimist-rpm-package-${{ github.run_id }}
        path: ./rpmbuild/RPMS/x86_64/kitimist-rpm-package-${{ github.run_id }}-x86_64.rpm 
